/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSeatingRouteImport } from './routes/_authenticated/dashboard.seating'
import { Route as AuthenticatedDashboardRsvpRouteImport } from './routes/_authenticated/dashboard.rsvp'
import { Route as AuthenticatedDashboardInvitationRouteImport } from './routes/_authenticated/dashboard.invitation'
import { Route as AuthenticatedDashboardInfoRouteImport } from './routes/_authenticated/dashboard.info'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminRevenueRouteImport } from './routes/_authenticated/admin.revenue'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedDashboardGuestsRouteImport } from './routes/_authenticated/dashboard.guests'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute = AuthenticatedAdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRevenueRoute = AuthenticatedAdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute = AuthenticatedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSeatingRoute =
  AuthenticatedDashboardSeatingRouteImport.update({
    id: '/seating',
    path: '/seating',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRsvpRoute =
  AuthenticatedDashboardRsvpRouteImport.update({
    id: '/rsvp',
    path: '/rsvp',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInvitationRoute =
  AuthenticatedDashboardInvitationRouteImport.update({
    id: '/invitation',
    path: '/invitation',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInfoRoute =
  AuthenticatedDashboardInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGuestsRoute =
  AuthenticatedDashboardGuestsRouteImport.update({
    id: '/guests',
    path: '/guests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/guests': typeof AuthenticatedDashboardGuestsRoute
  '/dashboard/info': typeof AuthenticatedDashboardInfoRoute
  '/dashboard/invitation': typeof AuthenticatedDashboardInvitationRoute
  '/dashboard/rsvp': typeof AuthenticatedDashboardRsvpRoute
  '/dashboard/seating': typeof AuthenticatedDashboardSeatingRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/guests': typeof AuthenticatedDashboardGuestsRoute
  '/dashboard/info': typeof AuthenticatedDashboardInfoRoute
  '/dashboard/invitation': typeof AuthenticatedDashboardInvitationRoute
  '/dashboard/rsvp': typeof AuthenticatedDashboardRsvpRoute
  '/dashboard/seating': typeof AuthenticatedDashboardSeatingRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/dashboard/guests': typeof AuthenticatedDashboardGuestsRoute
  '/_authenticated/dashboard/info': typeof AuthenticatedDashboardInfoRoute
  '/_authenticated/dashboard/invitation': typeof AuthenticatedDashboardInvitationRoute
  '/_authenticated/dashboard/rsvp': typeof AuthenticatedDashboardRsvpRoute
  '/_authenticated/dashboard/seating': typeof AuthenticatedDashboardSeatingRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/invite/$token'
    | '/dashboard/guests'
    | '/dashboard/info'
    | '/dashboard/invitation'
    | '/dashboard/rsvp'
    | '/dashboard/seating'
    | '/dashboard/settings'
    | '/admin/'
    | '/admin/users'
    | '/admin/subscriptions'
    | '/admin/revenue'
    | '/admin/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite/$token'
    | '/dashboard/guests'
    | '/dashboard/info'
    | '/dashboard/invitation'
    | '/dashboard/rsvp'
    | '/dashboard/seating'
    | '/dashboard/settings'
    | '/admin'
    | '/admin/users'
    | '/admin/subscriptions'
    | '/admin/revenue'
    | '/admin/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/invite/$token'
    | '/_authenticated/dashboard/guests'
    | '/_authenticated/dashboard/info'
    | '/_authenticated/dashboard/invitation'
    | '/_authenticated/dashboard/rsvp'
    | '/_authenticated/dashboard/seating'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/revenue'
    | '/_authenticated/admin/settings'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/revenue': {
      id: '/_authenticated/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AuthenticatedAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/seating': {
      id: '/_authenticated/dashboard/seating'
      path: '/seating'
      fullPath: '/dashboard/seating'
      preLoaderRoute: typeof AuthenticatedDashboardSeatingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rsvp': {
      id: '/_authenticated/dashboard/rsvp'
      path: '/rsvp'
      fullPath: '/dashboard/rsvp'
      preLoaderRoute: typeof AuthenticatedDashboardRsvpRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/invitation': {
      id: '/_authenticated/dashboard/invitation'
      path: '/invitation'
      fullPath: '/dashboard/invitation'
      preLoaderRoute: typeof AuthenticatedDashboardInvitationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/info': {
      id: '/_authenticated/dashboard/info'
      path: '/info'
      fullPath: '/dashboard/info'
      preLoaderRoute: typeof AuthenticatedDashboardInfoRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/guests': {
      id: '/_authenticated/dashboard/guests'
      path: '/guests'
      fullPath: '/dashboard/guests'
      preLoaderRoute: typeof AuthenticatedDashboardGuestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminRevenueRoute: typeof AuthenticatedAdminRevenueRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminRevenueRoute: AuthenticatedAdminRevenueRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardGuestsRoute: typeof AuthenticatedDashboardGuestsRoute
  AuthenticatedDashboardInfoRoute: typeof AuthenticatedDashboardInfoRoute
  AuthenticatedDashboardInvitationRoute: typeof AuthenticatedDashboardInvitationRoute
  AuthenticatedDashboardRsvpRoute: typeof AuthenticatedDashboardRsvpRoute
  AuthenticatedDashboardSeatingRoute: typeof AuthenticatedDashboardSeatingRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardGuestsRoute: AuthenticatedDashboardGuestsRoute,
    AuthenticatedDashboardInfoRoute: AuthenticatedDashboardInfoRoute,
    AuthenticatedDashboardInvitationRoute:
      AuthenticatedDashboardInvitationRoute,
    AuthenticatedDashboardRsvpRoute: AuthenticatedDashboardRsvpRoute,
    AuthenticatedDashboardSeatingRoute: AuthenticatedDashboardSeatingRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
